require_relative 'contact'
require_relative 'services'
require_relative 'shop'
require_relative 'basket'
require_relative 'order'
require_relative 'privacy'
require_relative 'policies'
require_relative 'success'
require_relative 'admin'
require_relative 'authentication'
require_relative 'joinus'
require_relative 'root' # Root last to make sure the get '/:city' doesn't interfere with other routes